### PR TITLE
examples: fix PapaDuck.ino usage of WiFiClientSecure.

### PR DESCRIPTION
**Pull request by rolsen**
- Added constant for DigiCert Global Root CA.
 - Added calls to WiFiClientSecure's `setCACert` and `connect`.
 - New constant for port 8883.

**Describe at a high level the solution you're providing**
WiFiClientSecure's `setCACert` and `connect` methods weren't getting called as per [WiFiClientSecure.ino](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/examples/WiFiClientSecure/WiFiClientSecure.ino).

**Is this a patch, a minor version change, or a major version change**
Patch

**Is this related to an open issue?**
No, but please let me know if you'd like me to create one. Submitting this PR seemed like the best way to start a conversation.

**Additional context**
[WiFiClientSecure docs](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/) say "Obtain the cert of the public CA". So went to internetofthings.ibmcloud.com, saw that it's [DigiCert Global Root CA](https://www.digicert.com/kb/digicert-root-certificates.htm). Then I downloaded that as a .pem and put it in PapaDuck.ino.

**Memory allocation failed**
After these changes, PapaDuck connects to Watson IoT, but I get a [loop of errors](https://gist.github.com/rolsen/2cfc65630d2de088f3fdec75e10bbbd3) about `[E][ssl_client.cpp:36] _handle_error(): [start_ssl_client():207]: (-32512) SSL - Memory allocation failed`. So that's going to be a separate issue. I'm running on a Heltec Wireless Stick Lite, which probably doesn't have the best memory stats. Maybe someone could try my code on something beefier?

**Unsecure?**
Is unsecure the better way to go? I figured security should be the default. Also, using the non-secure WiFiClient didn't work for me. I could dig into this to figure out exactly why not though.

### CODE REVIEW

**Comment by Evilgeniusnerd** [comment]
@rolsen  no this is great work. Really appreciate you looking into this seems a bit odd all the following errors you are getting. I think you are right though may just be board is out of memory. I have some ttgo t-beams here which is what we use a lot of the time I can try it on that and see what happens. Also as per your question for secure or not secure? I think it is best we use secure.

**Comment by Evilgeniusnerd** [comment]
@rolsen  I tried it out didn't get the same errors as you. Instead, my mqtt doesn't want to connect. 
`[INF: PapaDuck.cpp]  handleReceivedPacket() DONE

[PAPA] Failed to connect to 9c6nfo.messaging.internetofthings.ibmcloud.com:8883

`

**Comment by nfeuer** [comment]
Interesting. I will try this out today. Is it rebuilding a new certificate each time it tries to connect to MQTT? Is that why the heap keeps going down? It's a known issue that MQTT disconnects periodically, so the device will disconnect and reconnect multiple times even if it has an excellent connection.

**Comment by hawk4031** [comment]
@nfeuer It shouldn't be generating a new certificate every time. That's usually not the way certificates works, as they should be pretty static. There should be some ways we can test this to figure out what the problem could be, perhaps some sort of error codes we can look into that will give us more information.

**Comment by nfeuer** [comment]
Yeah, but what is it creating that is taking up memory? Also, why does it keep running the cert when it already connected. Does it run each time `WiFiClient.connect()` in loop? When memory allocation failed it became disconnected from wifi it looked like?

**Comment by nfeuer** [comment]
@rolsen how did you get the `ssl_client.cpp` output?

**Comment by rolsen** [comment]
@nfeuer, awesome. You're correct—`wifiClient.connect` should not be running at the top of `loop` unconditionally. I've moved it to while loop in `setup`. Now it's successfully connecting with [no error messages](https://gist.github.com/rolsen/619ef4cbdd03ddafe55706acee4b91d8). Next I'll be trying to get the Mama to talk to the Papa.

I got the ssl_client.cpp output by setting the Core Debug Level to Verbose:
Screen Shot 2021-06-04 at 14 00 28

**Comment by hawk4031** [comment]
Just to add some more comments here, the data transmission from the papa to the MQTT endpoint should be secure by default anyway. On IBM Watson IoT Platform, the 8883 port is TLS already, so I think if you're communicating with IoT Platform over this port, you shouldn't need to obtain their CA cert. 

That being said, if there is a compelling reason to do so, we should allow folks to choose when they are flashing their devices by making this configurable in the framework. Thoughts?

**Comment by nfeuer** [comment]
So I ran a bunch of testing yesterday and this looks good. If @hawk4031 said is true, then we should put this in an `ifdef` rather than create another example to maintain. I can do it later, or if anyone wants to push an update before we merge. Also, update the version numbers

**Comment by rolsen** [comment]
**Attempt: comment out**
Commenting out `wifiClient.setCACert(example_root_ca);` gives output more like:

```
17:38:08.775 -> [INF: DuckNet.cpp]  Duck connected to internet!
17:38:08.775 -> [INF: Duck.cpp]  setupInternet OK
17:38:08.775 -> [INF: PapaDuck.cpp]  setupWithDefaults done
17:38:10.951 -> [V][ssl_client.cpp:59] start_ssl_client(): Free internal heap before TLS 223312
17:38:10.951 -> [E][WiFiClientSecure.cpp:133] connect(): start_ssl_client: -1
17:38:10.951 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
17:38:10.951 -> [PAPA] Failed to connect to <redacted>.messaging.internetofthings.ibmcloud.com:8883
```

The [start_ssl_client: -1](https://github.com/espressif/arduino-esp32/blob/371f382db7dd36c470bb2669b222adf0a497600d/libraries/WiFiClientSecure/src/ssl_client.cpp#L61) comes from a mismatch between WiFiClientSecure's configurations. It assumes secure by default, but hasn't been given a rootCABuff, pskIdent, or psKey.

**Attempt: wifiClient.setInsecure()**
This connects, but gives a warning:

```
18:37:54.863 -> [INF: DuckNet.cpp]  Duck connected to internet!
18:37:54.901 -> [INF: Duck.cpp]  setupInternet OK
18:37:54.901 -> [INF: PapaDuck.cpp]  setupWithDefaults done
18:37:57.040 -> [V][ssl_client.cpp:59] start_ssl_client(): Free internal heap before TLS 223268
18:37:57.040 -> [V][ssl_client.cpp:67] start_ssl_client(): Starting socket
18:37:57.191 -> [V][ssl_client.cpp:106] start_ssl_client(): Seeding the random number generator
18:37:57.191 -> [V][ssl_client.cpp:115] start_ssl_client(): Setting up the SSL/TLS structure...
18:37:57.191 -> [I][ssl_client.cpp:129] start_ssl_client(): WARNING: Skipping SSL Verification. INSECURE!
18:37:57.191 -> [V][ssl_client.cpp:199] start_ssl_client(): Setting hostname for TLS session...
18:37:57.191 -> [V][ssl_client.cpp:214] start_ssl_client(): Performing the SSL/TLS handshake...
18:37:58.323 -> [V][ssl_client.cpp:235] start_ssl_client(): Verifying peer X.509 certificate...
18:37:58.323 -> [V][ssl_client.cpp:244] start_ssl_client(): Certificate verified.
18:37:58.323 -> [V][ssl_client.cpp:259] start_ssl_client(): Free internal heap after TLS 179868
18:37:58.512 -> [V][ssl_client.cpp:297] send_ssl_data(): Writing HTTP request with 67 bytes...
18:37:58.550 -> [PAPA] Mqtt client is connected!
```

**What's the basis for encryption with WiFiClientSecure?**
It sounds like [WiFiClientSecure has three encryption methods](https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFiClientSecure), but I may be missing something. If I understand correctly, the root CA cert allows WiFiClientSecure to verify that internetofthings.ibmcloud.com is really internetofthings.ibmcloud.com.

**Review by nfeuer — APPROVED** [review]

**Comment by nfeuer** [comment]
@rolsen you make a good point. This is what we have been seeing in the past but did not know it. We can include more documentation that mentions this. Looks pretty good as it is right now so I will merge it

**Pull request merged**
