### PR TITLE
Gps duck

### PR DESCRIPTION
**Pull request by r41d**
**Describe at a high level the solution you're providing**
Added a GPS Duck (to be flashed onto the TTGO T-Beam)

**Is this a patch, a minor version change, or a major version change**
Minor

**Is this related to an open issue?**
no

**Additional context**
GPS data can be helpful

### CODE REVIEW

**Review by nfeuer — APPROVED** [review]

**Comment by nfeuer** [comment]
Hi @r41d, this looks great! Love the callback from the captive portal message. We need more callbacks that can be used in different parts in the codebase.

**Comment by nfeuer** [comment]
@r41d can you update the version number in the following files?
DuckUtils.cpp
library.json
library.properties
README.md

Then this is ready for merge

**Comment by r41d** [comment]
What version bump would you recommend? `3.3.0` ?

**Comment by r41d** [comment]
One more thing I was wondering about, it seems not all dependencies that the project needs are listed in the library.json, is there a reason for that? 🤔

**Comment by r41d** [comment]
Yes, I'm currently getting into the specifics of the dependency topics.
The end goal is to no longer use submodules but the dependency resolution of PIO or Arduino, but this is a different topic than this feature, so see #280 for details

**Comment by krook** [comment]
Looks like this is approved @nfeuer? Anything else @r41d needs to look at?

**Comment by r41d** [comment]
I just now noticed that there already is a GPS example in the T-Beam examples folder, I have not seen this one before.
Don't think this additional GPS sketch is necessary then.

**Pull request closed without merging**
