### PR TITLE
Dependencies and Libraries overhaul

### PR DESCRIPTION
**Pull request by r41d**
**Describe at a high level the solution you're providing**
Migrate the project to dependency resolution rather than pulling them in via submodules.

**Is this a patch, a minor version change, or a major version change**
Minor, maybe major.

**Is this related to an open issue?**
See general channel in Slack

**Additional context**
Libraries via `git submodules` shouldn't be used.
We need Arduino IDE or PlatformIO either way, so why not use the dependency possibilities from there.

### CODE REVIEW

**Comment by krook** [comment]
> This PR is not probably yet ready for merging buy shall serve as a place to monitor the progress on this

Added the WIP (work in progress) flag until explicitly ready for merge

**Comment by r41d** [comment]
Aha, so there ARE differences between https://github.com/Project-Owl/Crypto and https://github.com/OperatorFoundation/Crypto.
Here they are: http://sprunge.us/j4FAaq
Even the official version from rweather (https://github.com/rweather/arduinolibs/tree/master/libraries/Crypto) does not contain a trace of this `hwcrypto` include.

Unfortunately the Project-Owl repo only contains one commit with the comment `init` and it is not clear which state this was.
Both the OperatorFoundation and the CDP version are "version 0.2.0" - despite they are different. This is not how a version number should work 😅

For PIO we could pull from a git repo, but I wouldn't want to pull a different library in PIO than in Arduino.

**Comment by BrentonPoke** [comment]
> The next problem would be:
> `.pio/libdeps/ttgo_lora32_v21/ArduinoOTA/src/InternalStorageESP.cpp:24:10: fatal error: Update.h: No such file or directory`
> This `Update.h` is also an arduino-esp32 internal, not sure how to approach that.

I could never figure out this part either, it puzzled me for hours and I never got anywhere.

**Comment by r41d** [comment]
Previously the CI used the CDP version from GitHub master which is kind of NOT the point of a CI, it should use the code that is currently in development. I added a workaround for this in the `.travis.yml`.
Sadly, I don't think we can expect the author (`me-no-dev`) of the AsyncTCP, ESPAsyncTCP and ESPAsyncWebServer libraries to react, the has not been any activity for years on those repos.

**Comment by nfeuer** [comment]
> Aha, so there ARE differences between https://github.com/Project-Owl/Crypto and https://github.com/OperatorFoundation/Crypto. Here they are: http://sprunge.us/j4FAaq Even the official version from rweather (https://github.com/rweather/arduinolibs/tree/master/libraries/Crypto) does not contain a trace of this `hwcrypto` include.
> 
> Unfortunately the Project-Owl repo only contains one commit with the comment `init` and it is not clear which state this was. Both the OperatorFoundation and the CDP version are "version 0.2.0" - despite they are different. This is not how a version number should work 😅
> 
> For PIO we could pull from a git repo, but I wouldn't want to pull a different library in PIO than in Arduino.
> 
> UPDATE: Building with PIO with the dependency
> 
> ```
> "external-repo": "https://github.com/Project-Owl/Crypto.git",
> ```
> 
> works but as I discussed I think we need another solution here. I opened a PR for updating the Crypto lib: [OperatorFoundation/Crypto#2](https://github.com/OperatorFoundation/Crypto/pull/2)
> 
> The next problem would be: `.pio/libdeps/ttgo_lora32_v21/ArduinoOTA/src/InternalStorageESP.cpp:24:10: fatal error: Update.h: No such file or directory` This `Update.h` is also an arduino-esp32 internal, not sure how to approach that.

@r41d, thank you for all the work you have put in so far! Sorry for the delay. So to give some context of the differences in the Crypto lib. When we first integrated it we were having issues with it recognizing the ESP32 platform with the defines to use the ESP32 settings. Set up a temporary solution so it would run and was planned to be readdressed with CDP Core. I would be interested to revisit this as getting it to work properly would be a better foundation for future updates. Not a big fan of our current solution so I can help revisit this and fix it.

Also, thank you for going through and fixing the copy/paste typos. 

I would like to know more about your workaround for the travis. As you stated, yes pulling from master was not ideal and we had been talking about how we wanted to implement a better solution. I will take another deeper look when I get back.

This is a great quality of life update and should be noted as a Minor version update instead of a patch. 

Great work

**Comment by TimoWielink** [comment]
@r41d How would you go about using the Libraries in IDE and PIO, I want to make sure the documentation reflects this PR.

**Comment by BrentonPoke** [comment]
We do need at least 4.5.0 for RadioLib, and somebody from the arduino project did respond in june:
`depends=RadioLib (>=4.6.0)` Seems to be what we're looking for.

**Comment by r41d** [comment]
> @r41d How would you go about using the Libraries in IDE and PIO, I want to make sure the documentation reflects this PR.

What exactly do you mean? The whole point of this Library overhaul is that everything related to dependencies happens automatically in the background without the need for manually downloading dependencies via submodules.

**Comment by TimoWielink** [comment]
So if I open open a example file of the CDP in the IDE it should automatically add all the libraries for compilation? Just wanna make sure the steps are correct

**Comment by r41d** [comment]
`library.json` is for PlatformIO and `library.properties` is for Arduino IDE.
An example would just need CPD as a singular dependency and then all dependencies of CDP will be pulled transitively.

**Comment by micheljung** [comment]
I'm new to this project and one of the first things I noticed is the many typos, lack of consistent naming, and some wrong documentation. This negatively impacted my trust in the code :)

Skimming over this PR, I'm happy to see that it fixed many typos etc. and proper dependency management is definitely something I'm looking forward, too.

**Review by TimoWielink — APPROVED** [review]

**Pull request merged**
